[package]
name = "kvstore-test"
version = "0.1.0"
authors = ["Greg Szabo <greg@philosobear.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
futures = "0.3"
tendermint = { version = "0.17.1", path = "../../tendermint" }
tendermint-light-client = { version = "0.17.1", path = "../../light-client" }
tendermint-rpc = { version = "0.17.1", path = "../../rpc", features = [ "http-client", "websocket-client" ] }
tokio = { version = "1.0", features = [ "rt-multi-thread", "macros" ] }
contracts = "0.4.0"
